create table if not exists public.runner_notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('xp','badge','level_up')),
  title text not null,
  body text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists runner_notifications_recipient_created_idx
  on public.runner_notifications(recipient_id, created_at desc);

alter table public.runner_notifications enable row level security;
revoke all on public.runner_notifications from public, anon;
grant select, update on public.runner_notifications to authenticated;

create policy "Runners read own notifications"
on public.runner_notifications for select to authenticated
using ((select auth.uid()) = recipient_id);

create policy "Runners mark own notifications read"
on public.runner_notifications for update to authenticated
using ((select auth.uid()) = recipient_id)
with check ((select auth.uid()) = recipient_id);

create or replace function public.road42_level(p_xp numeric)
returns integer language sql immutable set search_path = '' as $$
  select 1 + count(*)::integer
  from unnest(array[25,60,120,200,300,425,575,750,950]::numeric[]) threshold
  where p_xp >= threshold;
$$;

create or replace function public.notify_runner_activity()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  actor_name text;
  actor_character text;
  actor_public boolean;
  previous_xp numeric;
  current_xp numeric;
  previous_level integer;
  current_level integer;
begin
  if new.distance_km <= 0 or new.activity_type not in ('Easy','Quality','Long','run') then
    return new;
  end if;

  select display_name, character_key, is_public and setup_completed
  into actor_name, actor_character, actor_public
  from public.profiles where id = new.user_id;
  if not coalesce(actor_public, false) then return new; end if;

  select coalesce(sum(distance_km),0) into current_xp
  from public.activities
  where user_id = new.user_id and distance_km > 0
    and activity_type in ('Easy','Quality','Long','run');
  previous_xp := greatest(0, current_xp - new.distance_km);
  previous_level := public.road42_level(previous_xp);
  current_level := public.road42_level(current_xp);

  insert into public.runner_notifications(recipient_id,actor_id,kind,title,body,metadata)
  select p.id,new.user_id,'xp',actor_name||' gained XP',
    actor_name||' earned '||trim(to_char(new.distance_km,'FM999999990.0'))||' XP from a run.',
    jsonb_build_object('xp',new.distance_km,'total_xp',current_xp,'level',current_level,'character',actor_character)
  from public.profiles p
  where p.id <> new.user_id and p.setup_completed and p.is_public;

  if current_level > previous_level then
    insert into public.runner_notifications(recipient_id,actor_id,kind,title,body,metadata)
    values (new.user_id,new.user_id,'level_up','Level '||current_level||' reached!',
      actor_name||'''s '||initcap(actor_character)||' reached Level '||current_level||'.',
      jsonb_build_object('from_level',previous_level,'level',current_level,'character',actor_character));

    insert into public.runner_notifications(recipient_id,actor_id,kind,title,body,metadata)
    select p.id,new.user_id,'level_up',actor_name||' levelled up!',
      actor_name||'''s '||initcap(actor_character)||' reached Level '||current_level||'.',
      jsonb_build_object('from_level',previous_level,'level',current_level,'character',actor_character)
    from public.profiles p
    where p.id <> new.user_id and p.setup_completed and p.is_public;
  end if;
  return new;
end;
$$;

create or replace function public.notify_runner_badges()
returns trigger language plpgsql security definer set search_path = '' as $$
declare badge text;
begin
  if not (new.is_public and new.setup_completed) then return new; end if;
  foreach badge in array new.earned_rewards loop
    if not (badge = any(coalesce(old.earned_rewards,'{}'::text[]))) then
      insert into public.runner_notifications(recipient_id,actor_id,kind,title,body,metadata)
      select p.id,new.id,'badge',new.display_name||' earned a badge',
        new.display_name||' unlocked “'||badge||'”.',jsonb_build_object('badge',badge,'character',new.character_key)
      from public.profiles p
      where p.id <> new.id and p.setup_completed and p.is_public;
    end if;
  end loop;
  return new;
end;
$$;

create or replace function public.clear_private_runner_notifications()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if old.is_public and not new.is_public then
    delete from public.runner_notifications where actor_id = new.id and recipient_id <> new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists runner_activity_notifications on public.activities;
create trigger runner_activity_notifications after insert on public.activities
for each row execute function public.notify_runner_activity();

drop trigger if exists runner_badge_notifications on public.profiles;
create trigger runner_badge_notifications after update of earned_rewards on public.profiles
for each row when (old.earned_rewards is distinct from new.earned_rewards)
execute function public.notify_runner_badges();

drop trigger if exists runner_privacy_notifications on public.profiles;
create trigger runner_privacy_notifications after update of is_public on public.profiles
for each row execute function public.clear_private_runner_notifications();

revoke all on function public.road42_level(numeric) from public, anon, authenticated;
revoke all on function public.notify_runner_activity() from public, anon, authenticated;
revoke all on function public.notify_runner_badges() from public, anon, authenticated;
revoke all on function public.clear_private_runner_notifications() from public, anon, authenticated;

do $$ begin
  alter publication supabase_realtime add table public.runner_notifications;
exception when duplicate_object then null;
end $$;
