create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);
alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from public, anon, authenticated;

create table if not exists public.push_deliveries (
  notification_id bigint not null references public.runner_notifications(id) on delete cascade,
  subscription_id bigint not null references public.push_subscriptions(id) on delete cascade,
  status integer not null,
  attempted_at timestamptz not null default now(),
  primary key(notification_id, subscription_id)
);

alter table public.push_deliveries enable row level security;
revoke all on public.push_deliveries from public, anon, authenticated;

do $$
begin
  if not exists (select 1 from vault.secrets where name='road42_push_webhook') then
    perform vault.create_secret(encode(extensions.gen_random_bytes(32),'hex'),'road42_push_webhook','Authenticates notification inserts sent to the push Edge Function');
  end if;
end $$;

create or replace function public.get_push_config()
returns table(public_key text, private_key text, webhook_secret text)
language plpgsql security definer set search_path=''
as $$
begin
  if current_user not in ('service_role','postgres','supabase_admin') then raise exception 'not allowed'; end if;
  return query select
    (select decrypted_secret from vault.decrypted_secrets where name='road42_vapid_public' limit 1),
    (select decrypted_secret from vault.decrypted_secrets where name='road42_vapid_private' limit 1),
    (select decrypted_secret from vault.decrypted_secrets where name='road42_push_webhook' limit 1);
end;
$$;

create or replace function public.store_push_vapid(p_public text,p_private text)
returns void language plpgsql security definer set search_path=''
as $$
begin
  if current_user not in ('service_role','postgres','supabase_admin') then raise exception 'not allowed'; end if;
  if p_public !~ '^[A-Za-z0-9_-]{80,100}$' or p_private !~ '^[A-Za-z0-9_-]{40,50}$' then raise exception 'invalid key'; end if;
  if not exists (select 1 from vault.secrets where name='road42_vapid_public') then
    perform vault.create_secret(p_public,'road42_vapid_public','Road to 42 Web Push public key');
  end if;
  if not exists (select 1 from vault.secrets where name='road42_vapid_private') then
    perform vault.create_secret(p_private,'road42_vapid_private','Road to 42 Web Push private key');
  end if;
end;
$$;

revoke all on function public.get_push_config() from public,anon,authenticated;
revoke all on function public.store_push_vapid(text,text) from public,anon,authenticated;
grant execute on function public.get_push_config() to service_role;
grant execute on function public.store_push_vapid(text,text) to service_role;

create or replace function public.deliver_runner_push()
returns trigger language plpgsql security definer set search_path=''
as $$
declare secret text;
begin
  select decrypted_secret into secret from vault.decrypted_secrets where name='road42_push_webhook' limit 1;
  if secret is not null then
    perform net.http_post(
      url:='https://negkvlgimrthgonyvdqf.supabase.co/functions/v1/push-notifications',
      headers:=jsonb_build_object('Content-Type','application/json','x-road42-webhook',secret),
      body:=jsonb_build_object('notification_id',new.id),
      timeout_milliseconds:=10000
    );
  end if;
  return new;
end;
$$;

drop trigger if exists runner_notification_push on public.runner_notifications;
create trigger runner_notification_push after insert on public.runner_notifications
for each row execute function public.deliver_runner_push();
revoke all on function public.deliver_runner_push() from public,anon,authenticated;
