(function(){'use strict';
const URL='https://negkvlgimrthgonyvdqf.supabase.co',KEY='sb_publishable_RIt2HNAqPRO6vXMqWQEG3A_NJUHCj_t';
const sb=window.supabase?.createClient(URL,KEY),$=id=>document.getElementById(id);
let user=null,profile=null,logs=[],lastCelebration='';
const goalKm={'5K':5,'10K':10,'Half Marathon':21.1,'Marathon':42.2};
function weekStart(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function weekKm(){const s=weekStart();return logs.filter(x=>new Date(x.activity_date+'T12:00:00')>=s&&+x.distance_km>0).reduce((a,x)=>a+(+x.distance_km||0),0)}
function runs(){return logs.filter(x=>+x.distance_km>0&&['Easy','Quality','Long'].includes(x.activity_type))}
function streak(){const days=new Set(runs().map(x=>x.activity_date));let d=new Date();d.setHours(0,0,0,0);let k=d.toISOString().slice(0,10);if(!days.has(k)){d.setDate(d.getDate()-1);k=d.toISOString().slice(0,10);if(!days.has(k))return 0}let n=0;while(days.has(k)){n++;d.setDate(d.getDate()-1);k=d.toISOString().slice(0,10)}return n}
function renderJourney(){const box=$('journeyMap');if(!box||!profile)return;const total=runs().reduce((a,x)=>a+(+x.distance_km||0),0),target=goalKm[profile.goal]||42.2,stops=[['START',0],['5K',Math.min(5,target)],['10K',Math.min(10,target)],['HALF',Math.min(21.1,target)],['FINISH',target]];box.innerHTML=stops.map((s,i)=>{const done=total>=s[1]&&s[1]>0,cur=!done&&i===Math.max(0,stops.findIndex(x=>total<x[1]));return '<div class="journeyStop '+(done?'done ':'')+(cur?'current':'')+'"><div class="journeyDot">'+(done?'✓':i+1)+'</div><span>'+s[0]+'</span></div>'}).join('');$('journeyKm').textContent=total.toFixed(1)+' / '+target+' km';$('journeyMessage').textContent=total>=target?'Finish unlocked. Your next adventure is ready.':(target-total).toFixed(1)+' km until your next major checkpoint.'}
function renderRewards(){const box=$('rewardGrid');if(!box||!profile)return;const total=runs().reduce((a,x)=>a+(+x.distance_km||0),0),wk=weekKm(),rw=runs().filter(x=>new Date(x.activity_date+'T12:00:00')>=weekStart()).length,st=streak(),items=[['👟','First step',total>=1],['🔥','10 km total',total>=10],['🏅','Weekly goal',wk>=(+profile.weekly_km_target||25)],['⚡','Three runs',rw>=3],['🌿','Seven-day rhythm',st>=7],['🏆','Marathon distance',total>=42.2]];box.innerHTML=items.map(x=>'<div class="reward '+(x[2]?'unlocked':'')+'"><b class="rewardIcon">'+x[0]+'</b><span>'+x[1]+'</span></div>').join('');$('rewardCount').textContent=items.filter(x=>x[2]).length+'/'+items.length}
function renderStreak(){const n=streak();if(!$('streakCount'))return;$('streakCount').textContent=n+' day'+(n===1?'':'s');$('streakTitle').textContent=n?'Momentum unlocked':'Build your rhythm';$('streakMessage').textContent=n?'Keep it going. Your next consistency reward is '+Math.max(0,7-n)+' day'+(Math.max(0,7-n)===1?'':'s')+' away.':'No pressure—your comeback run starts whenever you are ready.'}
function renderChallenge(){const target=+profile?.weekly_km_target||25,current=weekKm();if($('challengeBarFill'))$('challengeBarFill').style.width=Math.min(100,current/target*100)+'%';if($('challengeProgress'))$('challengeProgress').textContent=current.toFixed(1)+' / '+target.toFixed(1)+' km';if($('challengeStatus'))$('challengeStatus').textContent=current>=target?'Challenge complete':'In progress'}
function renderAll(){if(profile){renderJourney();renderRewards();renderStreak();renderChallenge()}}
async function load(){if(!sb)return;const ses=await sb.auth.getSession();user=ses.data.session?.user;if(!user)return;const p=await sb.from('profiles').select('display_name,weekly_km_target,goal,race_date,setup_completed').eq('id',user.id).maybeSingle();if(p.error||!p.data?.setup_completed)return;profile=p.data;const a=await sb.from('activities').select('activity_date,activity_type,distance_km').eq('user_id',user.id).order('activity_date',{ascending:true});if(!a.error)logs=a.data||[];renderAll()}
async function renderWeeklyCompetition(){const box=$('leaderboard');if(!box||!profile||!sb)return;const start=weekStart().toISOString().slice(0,10),ps=await sb.from('profiles').select('id,display_name').eq('is_public',true).eq('setup_completed',true),as=await sb.from('activities').select('user_id,distance_km,activity_date').gte('activity_date',start);if(ps.error||as.error)return;const rows=(ps.data||[]).map(x=>({id:x.id,name:x.display_name||'Runner',km:(as.data||[]).filter(a=>a.user_id===x.id).reduce((n,a)=>n+(+a.distance_km||0),0)})).sort((a,b)=>b.km-a.km),me=rows.findIndex(x=>x.id===user?.id);let old=box.querySelector('.weeklyRank');if(!old){old=document.createElement('div');old.className='weeklyRank';box.prepend(old)}old.innerHTML=me<0?'Log a run to join this week’s challenge.':'<b>Weekly distance</b><br>You are <b>#'+(me+1)+'</b> with <b>'+rows[me].km.toFixed(1)+' km</b>. '+(me>0?'Your next place is '+rows[me-1].name+'.':'You are leading the group!')}
function celebration(){const form=$('checkinForm'),saved=$('saved');if(!form||!saved)return;let pending=0;form.addEventListener('submit',()=>{pending=+$('km').value||0},{capture:true});new MutationObserver(()=>{if(!saved.classList.contains('hidden')&&pending>0&&saved.textContent!==lastCelebration&&/saved/i.test(saved.textContent)){const msg='Run complete! <strong>+'+pending.toFixed(1)+' XP</strong> earned. Your runner moved '+pending.toFixed(1)+' km closer to the next checkpoint.';saved.innerHTML=msg;saved.classList.add('runCelebration');lastCelebration=msg;setTimeout(()=>{pending=0;load()},700)}}).observe(saved,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class']})}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-go="compete"]');if(b)setTimeout(renderWeeklyCompetition,700)});
celebration();setTimeout(load,900);setInterval(load,5000);
})();
